import type { TopicStatus } from './store';

// Using crypto.randomUUID() for IDs would be ideal, but for a static list, predictable IDs are fine.
// We will use a simple counter for this static data.
let idCounter = 0;
const generateId = () => (idCounter++).toString();

export const defaultNimetSyllabus: TopicStatus[] = [
  // 1. Mathematics
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Set Theory & Logic',
    topic: 'Sets and relations',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Set Theory & Logic',
    topic: 'Venn diagrams',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Set Theory & Logic',
    topic: 'Basic logic and truth tables',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Algebra',
    topic: 'Fundamental operations and quadratic equations',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Algebra',
    topic: 'Relations between roots and coefficients',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Algebra',
    topic: 'Indices, logarithms, and exponentials',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Algebra',
    topic: 'Progressions: Arithmetic (AP), Geometric (GP), and Harmonic (HP)',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Algebra',
    topic: 'Finite series',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Algebra',
    topic: 'Matrices and determinants',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Algebra',
    topic: 'Linear equations',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Algebra',
    topic: 'Permutations and Combinations',
    status: 'Not Started',
    priority: 'high',
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Algebra',
    topic: 'Binomial theorem',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Coordinate Geometry',
    topic: 'Cartesian coordinates, distance, and section formulas',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Coordinate Geometry',
    topic: 'Equations of a line in various forms and intersection of lines',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Coordinate Geometry',
    topic: 'Pairs of straight lines',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Coordinate Geometry',
    topic: 'Conic Sections: Circle, parabola, ellipse, and hyperbola',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Coordinate Geometry',
    topic: 'Tangents and normals to conics',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Calculus',
    topic: 'Limits and continuity',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Calculus',
    topic: 'Differentiation and its applications (tangents, normals)',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Calculus',
    topic: 'Maxima and minima',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Calculus',
    topic: 'Rolle’s and Mean Value Theorems',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Calculus',
    topic: 'Integration techniques: By parts, substitution, and partial fractions',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Calculus',
    topic: 'Definite integrals and area computations',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Trigonometry',
    topic: 'Trigonometric functions and identities',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Trigonometry',
    topic: 'Inverse trigonometric functions',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Trigonometry',
    topic: 'Solution of triangles',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Trigonometry',
    topic: 'Heights and distances',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Trigonometry',
    topic: 'Trigonometric equations',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Probability & Statistics',
    topic: 'Basic probability concepts',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Probability & Statistics',
    topic: 'Bayes’ theorem',
    status: 'Not Started',
    priority: 'high',
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Probability & Statistics',
    topic: 'Averages: Mean, median, and mode',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Probability & Statistics',
    topic: 'Measures of dispersion and frequency distributions',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Mathematics',
    chapter: 'Probability & Statistics',
    topic: 'Variance, moments, and percentiles',
    status: 'Not Started',
    priority: null,
  },

  // 2. Analytical Ability & Logical Reasoning
  {
    id: generateId(),
    subject: 'Analytical Ability & Logical Reasoning',
    chapter: 'Logical Reasoning',
    topic: 'Puzzles and seating arrangements (linear and circular)',
    status: 'Not Started',
    priority: 'high',
  },
  {
    id: generateId(),
    subject: 'Analytical Ability & Logical Reasoning',
    chapter: 'Logical Reasoning',
    topic: 'Blood relations and direction sense',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Analytical Ability & Logical Reasoning',
    chapter: 'Logical Reasoning',
    topic: 'Coding-decoding and alphanumeric series',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Analytical Ability & Logical Reasoning',
    chapter: 'Logical Reasoning',
    topic: 'Syllogisms, statements, and conclusions',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Analytical Ability & Logical Reasoning',
    chapter: 'Logical Reasoning',
    topic: 'Analogies and odd-one-out',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Analytical Ability & Logical Reasoning',
    chapter: 'Logical Reasoning',
    topic: 'Logical deductions and critical reasoning',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Analytical Ability & Logical Reasoning',
    chapter: 'Non-Verbal & Spatial Reasoning',
    topic: 'Mirror and water images',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Analytical Ability & Logical Reasoning',
    chapter: 'Non-Verbal & Spatial Reasoning',
    topic: 'Spatial (diagram-based) reasoning and pattern completions',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Analytical Ability & Logical Reasoning',
    chapter: 'Data Interpretation & Numerical Reasoning',
    topic: 'Data Interpretation: Charts (pie-charts), tables, and numeric graphs',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Analytical Ability & Logical Reasoning',
    chapter: 'Data Interpretation & Numerical Reasoning',
    topic: 'Data sufficiency',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Analytical Ability & Logical Reasoning',
    chapter: 'Data Interpretation & Numerical Reasoning',
    topic: 'Basic numerical reasoning tasks',
    status: 'Not Started',
    priority: null,
  },

  // 3. Computer Awareness
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Computer Basics',
    topic: 'Organization of a computer: CPU, Input/Output (I/O) devices',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Computer Basics',
    topic: 'Memory hierarchy: RAM, ROM, and cache memory',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Computer Basics',
    topic: 'Storage and backup systems',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Data Representation',
    topic: 'Number systems: Binary and hexadecimal',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Data Representation',
    topic: 'Binary arithmetic: Addition, subtraction, multiplication, division',
    status: 'Not Started',
    priority: 'high',
  },
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Data Representation',
    topic: 'Two’s complement and floating-point representation',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Data Representation',
    topic: 'Boolean Algebra: Logic gates (AND, OR, NAND, etc.), truth tables, and Boolean simplification',
    status: 'Not Started',
    priority: 'high',
  },
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Computer Software & Operating Systems',
    topic: 'Types of software: System software vs. application software',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Computer Software & Operating Systems',
    topic: 'Operating systems: Features of Windows, Linux, and Android',
    status: 'Not Started',
priority: null,
  },
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Computer Software & Operating Systems',
    topic: 'Utility programs',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Internet & Email',
    topic: 'Basic networking concepts and protocols',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Internet & Email',
    topic: 'Web browsing and email usage',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'Computer Awareness',
    chapter: 'Internet & Email',
    topic: 'Online security fundamentals',
    status: 'Not Started',
    priority: null,
  },

  // 4. General English
  {
    id: generateId(),
    subject: 'General English',
    chapter: 'Comprehension',
    topic: 'Reading comprehension passages (technical or general)',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'General English',
    chapter: 'Vocabulary',
    topic: 'Word meanings, synonyms, and antonyms',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'General English',
    chapter: 'Vocabulary',
    topic: 'Phrase usage and idioms',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'General English',
    chapter: 'Grammar & Usage',
    topic: 'Correct forms of verbs and tenses',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'General English',
    chapter: 'Grammar & Usage',
    topic: 'Prepositions and articles',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'General English',
    chapter: 'Grammar & Usage',
    topic: 'Sentence structure and error correction',
    status: 'Not Started',
    priority: null,
  },
  {
    id: generateId(),
    subject: 'General English',
    chapter: 'Writing Skills',
    topic: 'Technical writing basics and word power',
    status: 'Not Started',
    priority: null,
  },
];
